[versions]
androidGradlePlugin = "9.0.1"
androidxCore = "1.18.0"
androidxActivity = "1.13.0"
junit = "4.13.2"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
